version: 0.2

phases:
  install:
    commands:
      - echo "Instalando dependências..."
      - pnpm install

  build:
    commands:
      - echo "Construindo aplicação..."
      - pnpm run build

artifacts:
  files:
    - "**/*"